stages:
  - fetch
  - create_venv
  - deploy

# Clone de repository naar de server
fetch:
  image: ubuntu:latest
  stage: fetch
  only:
    - Stijn
  tags:
    - rpi_runner
  script:
    - cd /var/www/
    # Check of de folder bestaat en verwijder die
    - if [ -d "$REPO_NAME" ]; then rm -rf "$REPO_NAME"; fi
    # Clone de repository
    - git clone https://oauth2:$ACCESS_TOKEN_RPI@gitlab.fdmci.hva.nl/$REPO_URL
    - cd /var/www/$REPO_NAME


# Download en installeer de benodigde dependencies
create_venv:
  image: python:latest
  stage: create_venv
  only:
    - Stijn
  tags:
    - rpi_runner
  script:
    - cd /var/www/$REPO_NAME
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt

# Deploy de applicatie door de service te herstarten
deploy:
  image: ubuntu:latest
  stage: deploy
  only:
    - Stijn
  tags:
    - rpi_runner
  script:
    - cd /var/www/$REPO_NAME
    - git remote set-url origin https://oauth2:$ACCESS_TOKEN_RPI@gitlab.fdmci.hva.nl/propedeuse-hbo-ict/onderwijs/student-projecten/2025-2026/spiegelonderwijs-bim/b3-2425-deopdracht/dooyoogeequu34/
    - git checkout Stijn
    - git pull origin Stijn
    - sudo /bin/systemctl restart flaskapp.service
