stages:
  - deploy

deploy:
  image: ubuntu:latest
  stage: deploy
  only:
    - Stijn
  tags:
    - deploy

  before_script:
    - ssh $SSH_USER@$SSH_HOST

  script:
    - "cd $WORK_DIR && git checkout Stijn && git pull && exit"

  after_script:
    - rm -rf ~/.ssh
