-- MySQL Script generated by MySQL Workbench
-- Tue Oct 28 11:53:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phonenumber` INT(12) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `dateCreated` VARCHAR(45) NULL,
  `timeCreated` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NewsArticle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NewsArticle` (
  `newsArticle_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `publishDate` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `summary` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`newsArticle_id`, `User_user_id`),
  INDEX `fk_NewsArticle_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_NewsArticle_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subscription` (
  `subscription_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `dateCreated` VARCHAR(45) NULL,
  `timeCreated` VARCHAR(45) NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`subscription_id`, `User_user_id`),
  INDEX `fk_Subscription_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Subscription_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SupportTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SupportTicket` (
  `ticket_id` INT NOT NULL,
  `ticket_subject` VARCHAR(255) NOT NULL,
  `ticket_category` VARCHAR(255) NOT NULL,
  `ticket_message` VARCHAR(9999) NOT NULL,
  `ticket_date` DATE NOT NULL,
  `ticket_time` TIME NOT NULL,
  `ticket_priority` INT NOT NULL,
  `ticket_open_status` TINYINT NOT NULL,
  `ticket_close_reason` VARCHAR(255) NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`, `User_user_id`),
  INDEX `fk_SupportTicket_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_SupportTicket_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_User` (
  `Product_product_id` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`Product_product_id`, `User_user_id`),
  INDEX `fk_Product_has_User_User1_idx` (`User_user_id` ASC) VISIBLE,
  INDEX `fk_Product_has_User_Product_idx` (`Product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_User_Product`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_User_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Subscription` (
  `User_user_id` INT NOT NULL,
  `Subscription_subscription_id` INT NOT NULL,
  PRIMARY KEY (`User_user_id`, `Subscription_subscription_id`),
  INDEX `fk_User_has_Subscription_Subscription1_idx` (`Subscription_subscription_id` ASC) VISIBLE,
  INDEX `fk_User_has_Subscription_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Subscription_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Subscription_Subscription1`
    FOREIGN KEY (`Subscription_subscription_id`)
    REFERENCES `mydb`.`Subscription` (`subscription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidents` (
  `incidents_id` INT NOT NULL,
  `incident_subject` VARCHAR(255) NOT NULL,
  `incident_category` VARCHAR(255) NOT NULL,
  `incident_message` VARCHAR(9999) NOT NULL,
  `incident_date` DATE NOT NULL,
  `incident_time` TIME NOT NULL,
  `incident_priority` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`incidents_id`, `User_user_id`),
  INDEX `fk_incidents_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_incidents_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Role` (
  `user_role_id` INT NOT NULL,
  `role_name` VARCHAR(255) NOT NULL,
  `role_priority` VARCHAR(255) NOT NULL,
  `role_assign_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`user_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Permissions_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Permissions_has_User` (
  `User_Permissions_user_permissions_id` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`User_Permissions_user_permissions_id`, `User_user_id`),
  INDEX `fk_User_Permissions_has_User_User1_idx` (`User_user_id` ASC) VISIBLE,
  INDEX `fk_User_Permissions_has_User_User_Permissions1_idx` (`User_Permissions_user_permissions_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Permissions_has_User_User_Permissions1`
    FOREIGN KEY (`User_Permissions_user_permissions_id`)
    REFERENCES `mydb`.`User_Role` (`user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Permissions_has_User_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Role_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Role_has_User` (
  `User_Role_user_role_id` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`User_Role_user_role_id`, `User_user_id`),
  INDEX `fk_User_Role_has_User_User1_idx` (`User_user_id` ASC) VISIBLE,
  INDEX `fk_User_Role_has_User_User_Role1_idx` (`User_Role_user_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role_has_User_User_Role1`
    FOREIGN KEY (`User_Role_user_role_id`)
    REFERENCES `mydb`.`User_Role` (`user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role_has_User_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
