-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 22:47:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`NewsArticle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NewsArticle` (
  `newsArticle_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `author` VARCHAR(100) NULL,
  `publish_date` TIMESTAMP NULL,
  `status` VARCHAR(50) NULL DEFAULT 'draft',
  PRIMARY KEY (`newsArticle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `product_type` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `availability_status` VARCHAR(50) NULL DEFAULT 'available',
  `date_added` TIMESTAMP NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_User` (
  `Product_product_id` INT(11) NOT NULL,
  `User_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`Product_product_id`, `User_user_id`),
  INDEX `fk_Product_has_User_Product_idx` (`Product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_User_Product`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SupportTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SupportTicket` (
  `ticket_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ticket_subject` VARCHAR(255) NOT NULL,
  `ticket_category` VARCHAR(255) NULL,
  `ticket_message` TEXT NOT NULL,
  `ticket_date` TIMESTAMP NULL,
  `ticket_priority` VARCHAR(50) NULL DEFAULT 'low',
  `ticket_open_status` TINYINT NULL DEFAULT 1,
  `ticket_close_reason` TEXT NULL,
  PRIMARY KEY (`ticket_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Role` (
  `user_role_id` INT(11) NOT NULL,
  `role_name` VARCHAR(255) NOT NULL,
  `role_priority` VARCHAR(255) NOT NULL,
  `role_assign_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`user_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Role_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Role_has_User` (
  `User_Role_user_role_id` INT(11) NOT NULL,
  `User_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`User_Role_user_role_id`, `User_user_id`),
  INDEX `fk_User_Role_has_User_User_Role1_idx` (`User_Role_user_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role_has_User_User_Role1`
    FOREIGN KEY (`User_Role_user_role_id`)
    REFERENCES `mydb`.`User_Role` (`user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phonenumber` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL,
  `postalcode` VARCHAR(20) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL DEFAULT 'Nederland',
  `date_added` TIMESTAMP NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phonenumber` INT(12) NULL DEFAULT NULL,
  `position` VARCHAR(255) NULL,
  `departement` VARCHAR(255) NULL,
  `hire_date` DATE NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Incidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Incidents` (
  `incidents_id` INT(11) NOT NULL AUTO_INCREMENT,
  `incident_subject` VARCHAR(255) NOT NULL,
  `incident_category` VARCHAR(255) NOT NULL,
  `incident_message` TEXT NOT NULL,
  `incident_date` TIMESTAMP NULL,
  `incident_priority` VARCHAR(50) NULL DEFAULT low,
  `Customer_customer_id` INT(11) NOT NULL,
  `Employee_employee_id` INT(11) NOT NULL,
  PRIMARY KEY (`incidents_id`, `Customer_customer_id`, `Employee_employee_id`),
  INDEX `fk_Incidents_Customer1_idx` (`Customer_customer_id` ASC) VISIBLE,
  INDEX `fk_Incidents_Employee1_idx` (`Employee_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Incidents_Customer1`
    FOREIGN KEY (`Customer_customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidents_Employee1`
    FOREIGN KEY (`Employee_employee_id`)
    REFERENCES `mydb`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medewerker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medewerker` (
  `medewerker_id` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  PRIMARY KEY (`medewerker_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phonenumber` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL,
  `postalcode` VARCHAR(20) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL DEFAULT 'Nederland',
  `date_added` TIMESTAMP NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `phone` VARCHAR(20) NULL,
  `date_added` TIMESTAMP NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `Company_company_id` INT NOT NULL,
  `contract_name` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `date_added` TIMESTAMP NULL,
  PRIMARY KEY (`contract_id`, `Company_company_id`),
  INDEX `fk_Contract_Company1_idx` (`Company_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Company1`
    FOREIGN KEY (`Company_company_id`)
    REFERENCES `mydb`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_has_Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_has_Company` (
  `Customer_customer_id` INT(11) NOT NULL,
  `Company_company_id` INT NOT NULL,
  PRIMARY KEY (`Customer_customer_id`, `Company_company_id`),
  INDEX `fk_Customer_has_Company_Company1_idx` (`Company_company_id` ASC) VISIBLE,
  INDEX `fk_Customer_has_Company_Customer1_idx` (`Customer_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Company_Customer1`
    FOREIGN KEY (`Customer_customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Company_Company1`
    FOREIGN KEY (`Company_company_id`)
    REFERENCES `mydb`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_has_SupportTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_has_SupportTicket` (
  `Customer_customer_id` INT(11) NOT NULL,
  `SupportTicket_ticket_id` INT(11) NOT NULL,
  PRIMARY KEY (`Customer_customer_id`, `SupportTicket_ticket_id`),
  INDEX `fk_Customer_has_SupportTicket_SupportTicket1_idx` (`SupportTicket_ticket_id` ASC) VISIBLE,
  INDEX `fk_Customer_has_SupportTicket_Customer1_idx` (`Customer_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_SupportTicket_Customer1`
    FOREIGN KEY (`Customer_customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_SupportTicket_SupportTicket1`
    FOREIGN KEY (`SupportTicket_ticket_id`)
    REFERENCES `mydb`.`SupportTicket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Contract` (
  `Product_product_id` INT(11) NOT NULL,
  `Contract_contract_id` INT NOT NULL,
  `Contract_Company_company_id` INT NOT NULL,
  PRIMARY KEY (`Product_product_id`, `Contract_contract_id`, `Contract_Company_company_id`),
  INDEX `fk_Product_has_Contract_Contract1_idx` (`Contract_contract_id` ASC, `Contract_Company_company_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Contract_Product1_idx` (`Product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Contract_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Contract_Contract1`
    FOREIGN KEY (`Contract_contract_id` , `Contract_Company_company_id`)
    REFERENCES `mydb`.`Contract` (`contract_id` , `Company_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
